const arrayCategories = [
  { label: "HTML5" },
  { label: "CSS3" },
  { label: "JavaScript" },
  { label: "Front-end" },
  { label: "Back-end" },
  { label: "Full-stack" },
  { label: "Web design" },
  { label: "Responsive" },
  { label: "UX/UI" },
  { label: "API" },
  { label: "Database" },
  { label: "Git / GitHub / GitLab" },
  { label: "DevOps" },
  { label: "Agile / Scrum" },
  { label: "CI/CD" },
  { label: "Test-driven development (TDD)" },
  { label: "CMS" },
  { label: "Cybersecurity" },
  { label: "Cloud" },
  { label: "hosting" },
  { label: "SEO" },
  { label: "Authentification" },
  { label: "Accessibilité" },
  { label: "IoT" },
  { label: "Blockchain" },
  { label: "Docker" },
  { label: "WebAssembly" },
  { label: "scraping" },
  { label: "tests" },
  { label: "TCP/IP" },
  { label: "HTTP/HTTPS" },
  { label: "PHP" },
  { label: "Python" },
  { label: "Ruby" },
  { label: "Java" },
  { label: "C#" },
  { label: "TypeScript" },
  { label: "Node.js" },
  { label: "SQL" },
  { label: "NoSQL" },
  { label: "Swift" },
  { label: "Go " },
  { label: "Rust" },
  { label: "bash / PowerShell" },
  { label: "Dart" },
  { label: "Kotlin" },
  { label: "React.js" },
  { label: "Angular" },
  { label: "Vue.js" },
  { label: "Express.js" },
  { label: "Django" },
  { label: "Spring Boot" },
  { label: "Flask " },
  { label: "Laravel " },
  { label: ".NET" },
  { label: "Symfony  " },
  { label: "Next.js" },
  { label: "Svelte" },
];

export default arrayCategories;
